### ISSUE TITLE
Questions on generating the dataset

### ISSUE THREAD

**Issue by anirjoshi** [SRI-CSL/AircraftVerse#1]
Hello,
This is a very interesting work. The [paper](https://arxiv.org/abs/2306.05562) does not talk much about how this dataset is generated. Also, there is a talk of a grammar for generating the dataset, what is this grammar, is it formally presented somewhere? It seems that this data is sampled from a probabilistic generator, is this generator code available in this repo?

Thanks

**Comment by susmitjha** [comment]
Thank you for your interest! Yes, AircraftVerse is the dataset of aircraft designs, and not the AI co-designer (which is generic and can design different kinds of CPS). The effort is funded by DARPA. We don't have permission for complete release of the AI co-designer yet. But bits and pieces of it are described in the following papers: https://arxiv.org/pdf/2211.08138.pdf , Direct Amortized Likelihood Ratio Estimation. Adam D. Cobb; Brian Matejek; Daniel Elenius; Anirban Roy; Susmit Jha at AAAI'24, and https://www.cambridge.org/core/journals/proceedings-of-the-design-society/article/on-diverse-systemlevel-design-using-manifold-learning-and-partial-simulated-annealing/58C33505893DE15D2D6589E98C5F55BA .

**Comment by anirjoshi** [comment]
Hi, 
Thank you for the response. The papers do talk about the generation process in bits and pieces. Does this repo include those bits and pieces. For example: does the file [schema/uav_schema.json](https://github.com/SRI-CSL/AircraftVerse/blob/375810970100ccd9626ee2e08f2b8b332afd32cd/schema/uav_schema.json), describe the grammar for generating UAV designs? Also, does the [code file](https://github.com/SRI-CSL/AircraftVerse/tree/375810970100ccd9626ee2e08f2b8b332afd32cd/prob_gen) correspond to the random UAV generator?

Thanks

**Comment by susmitjha** [comment]
Thank you. Yes, these are parts of the generator (those that have been cleared for public release). We put out as much collateral as essential for the dataset paper:  https://papers.nips.cc/paper_files/paper/2023/hash/8b94879b177d9780c17f5a78f62a6a8a-Abstract-Datasets_and_Benchmarks.html . Please feel free to contact us at susmit.jha@sri.com and adam.cobb@sri.com if you have something specific in mind.
